### PR TITLE
Support Passt Network Binding Plugin for IPv6 environments.

### PR DESCRIPTION
**Pull request by trevex**
Changes required to use different network binding plugin for IPv6 environments.

### CODE REVIEW

**Comment by trevex** [comment]
@Unix4ever The PR should now be ready, but not sure why `conform/commit/gpg-identity` is failing. GPG key is published to ubuntu and openpgp keyserver.

**Comment by trevex** [comment]
Alternatively I can also refactor the code to get network configuration from provider data instead.
That is how I added support to configure the target namespace to provision to (future PR: https://github.com/trevex/omni-infra-provider-kubevirt/commit/283a744da2bf0e104ee626ddd6e904d7dad59b9b).

**Comment by trevex** [comment]
I am assuming the conform check is failing due to this: https://github.com/siderolabs/omni-infra-provider-kubevirt/blob/main/.conform.yaml#L12

**Comment by Unix4ever** [comment]
> @Unix4ever The PR should now be ready, but not sure why conform/commit/gpg-identity is failing. GPG key is published to ubuntu and openpgp keyserver.

This is expected. The PR is needed to be signed by one of the Sidero employees.

> Alternatively I can also refactor the code to get network configuration from provider data instead.

I think that's a good idea. You can make it optional with the default value of bridge.

I will sign and merge the PR when it's ready.

**Comment by trevex** [comment]
Done, once this is merged I'll create another PR to configure target namespace through provider data as well.

**Review by Unix4ever — APPROVED** [review]

**Comment by Unix4ever** [comment]
Ah, I won't be able to merge this PR as it's created from the `main` branch of your fork.
I will recreate the PR using your commit in my fork

**Comment by Unix4ever** [comment]
replaced with https://github.com/siderolabs/omni-infra-provider-kubevirt/pull/4

**Pull request closed without merging**
